package upcomingTasks;

import javax.swing.JOptionPane;
import Menu.Menu;
import Overview.OverviewPanel;
import Settings.SettingsPanel;
import Tasks.SoloTaskPanel;

import java.awt.BorderLayout;
import java.awt.Container;

import javax.swing.*;

import javax.swing.JButton;
import javax.swing.JOptionPane;

import Classes.User;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AmirrezaKhoshbakht
 */
public class upcomingTask extends javax.swing.JPanel {
        // TEST DELETE FROM FINAL CODE
        User user;

        /**
         * Creates new form upcomingTask
         */
        public upcomingTask(User user) {
                this.user = user;
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                headerPanel = new javax.swing.JPanel();
                goBackButton = new javax.swing.JButton();
                profileLabel = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("MMMM dd, E");
                java.time.LocalDateTime now = java.time.LocalDateTime.now();
                jLabel1 = new javax.swing.JLabel();
                task1 = new javax.swing.JCheckBox();
                task2 = new javax.swing.JCheckBox();
                task3 = new javax.swing.JCheckBox();
                task4 = new javax.swing.JCheckBox();
                sorting = new javax.swing.JComboBox<>();
                showAllTask = new javax.swing.JButton();
                task1groups = new javax.swing.JLabel();
                task2groups = new javax.swing.JLabel();
                task3groups = new javax.swing.JLabel();
                task4groups = new javax.swing.JLabel();
                task1DueDate = new javax.swing.JLabel();
                task2DueDate = new javax.swing.JLabel();
                task3DueDate = new javax.swing.JLabel();
                task4DueDate = new javax.swing.JLabel();
                editTask1 = new javax.swing.JButton();
                editTask2 = new javax.swing.JButton();
                editTask3 = new javax.swing.JButton();
                editTask4 = new javax.swing.JButton();
                addNewTaskButton = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                completedTask1 = new javax.swing.JLabel();
                completedTask2 = new javax.swing.JLabel();
                completedTask3 = new javax.swing.JLabel();
                allCompletedTasks = new javax.swing.JButton();

                goBackButton.setText("< Home");
                goBackButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

                profileLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
                profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                profileLabel.setText("Upcoming Tasks");

                javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
                headerPanel.setLayout(headerPanelLayout);
                headerPanelLayout.setHorizontalGroup(headerPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(headerPanelLayout.createSequentialGroup()
                                                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(173, 173, 173)
                                                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 413,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));
                headerPanelLayout.setVerticalGroup(headerPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(headerPanelLayout.createSequentialGroup().addGroup(headerPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(goBackButton).addComponent(profileLabel))
                                                .addGap(0, 17, Short.MAX_VALUE)));

                jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
                jLabel1.setText(dtf.format(now));

                task1.setBackground(new java.awt.Color(255, 255, 0));
                task1.setText("No Data");
                if (user.taskList.size() != 0) {
                        task1.setText(user.taskList.get(user.taskList.size() - 1).getTitle() + ", xp: "
                                        + user.taskList.get(user.taskList.size() - 1).xpReward);
                }
                task1.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                task1StateChanged(evt);
                        }
                });
                task1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                task1ActionPerformed(evt);
                        }
                });

                task2.setBackground(new java.awt.Color(255, 102, 51));
                task2.setText("No Data");
                if (user.taskList.size() > 1) {
                        task2.setText(user.taskList.get(user.taskList.size() - 2).getTitle() + ", xp: "
                                        + user.taskList.get(user.taskList.size() - 2).xpReward);
                }
                task2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                task2ActionPerformed(evt);
                        }
                });

                task3.setBackground(new java.awt.Color(255, 102, 51));
                task3.setText("No Data");
                if (user.taskList.size() > 2) {
                        task3.setText(user.taskList.get(user.taskList.size() - 3).getTitle() + ", xp: "
                                        + user.taskList.get(user.taskList.size() - 3).xpReward);
                }
                task3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                task3ActionPerformed(evt);
                        }
                });

                task4.setBackground(new java.awt.Color(0, 204, 255));
                task4.setText("No Data");
                if (user.taskList.size() > 3) {
                        task4.setText(user.taskList.get(user.taskList.size() - 4).getTitle() + ", xp: "
                                        + user.taskList.get(user.taskList.size() - 4).xpReward);
                }
                task4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                task4ActionPerformed(evt);
                        }
                });

                sorting.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Sort By", "Date", "Priority", "Category" }));

                showAllTask.setText("All Tasks");

                task1groups.setText("No Data");
                if (user.taskList.size() != 0) {
                        task1groups.setText(user.taskList.get(user.taskList.size() - 1).getCategory());
                }

                task2groups.setText("No Data");
                if (user.taskList.size() > 1) {
                        task2groups.setText(user.taskList.get(user.taskList.size() - 2).getCategory());
                }

                task3groups.setText("No Data");
                if (user.taskList.size() > 2) {
                        task2groups.setText(user.taskList.get(user.taskList.size() - 3).getCategory());
                }

                task4groups.setText("No Data");
                if (user.taskList.size() > 3) {
                        task2groups.setText(user.taskList.get(user.taskList.size() - 4).getCategory());
                }

                task1DueDate.setText("No Data");
                if (user.taskList.size() != 0) {
                        task1DueDate.setText(user.taskList.get(user.taskList.size() - 1).getDate().toString() + ", "
                                        + user.taskList.get(user.taskList.size() - 1).getTime().toString());
                }

                task2DueDate.setText("No Data");
                if (user.taskList.size() > 1) {
                        task2DueDate.setText(user.taskList.get(user.taskList.size() - 2).getDate().toString() + ", "
                                        + user.taskList.get(user.taskList.size() - 2).getTime().toString());
                }

                task3DueDate.setText("No Data");
                if (user.taskList.size() > 2) {
                        task3DueDate.setText(user.taskList.get(user.taskList.size() - 3).getDate().toString() + ", "
                                        + user.taskList.get(user.taskList.size() - 3).getTime().toString());
                }

                task4DueDate.setText("No Data");
                if (user.taskList.size() > 3) {
                        task4DueDate.setText(user.taskList.get(user.taskList.size() - 4).getDate().toString() + ", "
                                        + user.taskList.get(user.taskList.size() - 4).getTime().toString());
                }

                editTask1.setText("Edit");
                editTask1.setBorder(null);
                editTask1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                editTask1ActionPerformed(evt);
                        }
                });

                editTask2.setText("Edit");
                editTask2.setBorder(null);

                editTask3.setText("Edit");
                editTask3.setBorder(null);

                editTask4.setText("Edit");
                editTask4.setBorder(null);

                addNewTaskButton.setBackground(new java.awt.Color(51, 255, 153));
                addNewTaskButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                addNewTaskButton.setText("Add New Task");
                addNewTaskButton.setBorder(
                                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
                                                new java.awt.Color(51, 255, 102), new java.awt.Color(51, 255, 102),
                                                new java.awt.Color(0, 255, 102), new java.awt.Color(51, 255, 102)));
                addNewTaskButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addNewTaskButtonActionPerformed(evt);
                        }
                });

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel2.setText("Category");

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel3.setText("Due Time");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(42, 42, 42)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(task3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                178,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(task4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                170,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(task1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                176,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(task2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                184,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(task3groups,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                76,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(task2groups,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                82,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(task1groups,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                101,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(task4groups,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                68,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(task4DueDate,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                128,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(task3DueDate,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                121,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGap(65, 65, 65))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(41, 41, 41)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel3)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(task1DueDate,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                133,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(task2DueDate,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                                .addGap(60, 60, 60)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(editTask2)
                                                                                                .addComponent(editTask1)
                                                                                                .addComponent(editTask3)
                                                                                                .addComponent(editTask4)))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(sorting,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                128,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(showAllTask,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                130,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                283,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(508, 508,
                                                                                                                                508)
                                                                                                                .addComponent(addNewTaskButton))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(245, 245,
                                                                                                                                245)
                                                                                                                .addComponent(jLabel2)))))
                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                99,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(addNewTaskButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                63,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel2).addComponent(jLabel3)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(task1).addComponent(editTask1)
                                                                .addComponent(task1groups).addComponent(task1DueDate))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(task2).addComponent(task2groups)
                                                                .addComponent(task2DueDate).addComponent(editTask2))
                                                .addGap(13, 13, 13)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(task3).addComponent(task3groups)
                                                                .addComponent(task3DueDate).addComponent(editTask3))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(task4).addComponent(task4groups)
                                                                .addComponent(task4DueDate).addComponent(editTask4))
                                                .addGap(32, 32, 32)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(showAllTask).addComponent(sorting,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap()));

                jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel10.setText("Completed");

                completedTask1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                completedTask1.setText("No Data");
                if (user.completedTasks.size() != 0) {
                        completedTask1.setText(user.completedTasks.get(user.completedTasks.size() - 1).getTitle());
                }

                completedTask2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                completedTask2.setText("No Data");
                if (user.completedTasks.size() > 1) {
                        completedTask2.setText(user.completedTasks.get(user.completedTasks.size() - 2).getTitle());
                }

                completedTask3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                completedTask3.setText("No Data");
                if (user.completedTasks.size() > 2) {
                        completedTask3.setText(user.completedTasks.get(user.completedTasks.size() - 3).getTitle());
                }

                allCompletedTasks.setText("All Completed Tasks");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(36, 36, 36)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(completedTask1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                168,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                224,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(completedTask2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                224,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(completedTask3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                224,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(allCompletedTasks,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                224,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(29, 29, 29)
                                                .addComponent(jLabel10).addGap(43, 43, 43).addComponent(completedTask1)
                                                .addGap(18, 18, 18).addComponent(completedTask2).addGap(18, 18, 18)
                                                .addComponent(completedTask3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32,
                                                                Short.MAX_VALUE)
                                                .addComponent(allCompletedTasks).addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68,
                                                                Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
        }// </editor-fold>//GEN-END:initComponents

        private void task1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_task1ActionPerformed
                // TODO add your handling code here:
                if (user.taskList.size() != 0) {
                        user.completeTask(user.taskList.get(user.taskList.size() - 1));
                        this.removeAll();
                        initComponents();
                        repaint();
                        revalidate();
                        JOptionPane.showMessageDialog(null, "Task Completed!!");
                }

        }// GEN-LAST:event_task1ActionPerformed

        private void task2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_task2ActionPerformed
                // TODO add your handling code here:
                if (user.taskList.size() > 1) {
                        user.completeTask(user.taskList.get(user.taskList.size() - 2));
                        this.removeAll();
                        initComponents();
                        repaint();
                        revalidate();
                        JOptionPane.showMessageDialog(null, "Task Completed!!");
                }
        }// GEN-LAST:event_task2ActionPerformed

        private void task1StateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_task1StateChanged
                // TODO add your handling code here:

        }// GEN-LAST:event_task1StateChanged

        private void task3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_task3ActionPerformed
                // TODO add your handling code here:
                if (user.taskList.size() > 2) {
                        user.completeTask(user.taskList.get(user.taskList.size() - 3));
                        this.removeAll();
                        initComponents();
                        repaint();
                        revalidate();
                        JOptionPane.showMessageDialog(null, "Task Completed!!");
                }
        }// GEN-LAST:event_task3ActionPerformed

        private void task4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_task4ActionPerformed
                // TODO add your handling code here:
                if (user.taskList.size() > 3) {
                        user.completeTask(user.taskList.get(user.taskList.size() - 4));
                        this.removeAll();
                        initComponents();
                        repaint();
                        revalidate();
                        JOptionPane.showMessageDialog(null, "Task Completed!!");
                }
        }// GEN-LAST:event_task4ActionPerformed

        private void addNewTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addNewTaskButtonActionPerformed

                JPanel otherPanel = new SoloTaskPanel(user);
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

                Container contain = frame.getContentPane();
                contain.removeAll();
                contain.add(new Menu(user), BorderLayout.WEST);
                contain.add(otherPanel, BorderLayout.CENTER);
                contain.revalidate();
                contain.setVisible(true);

        }// GEN-LAST:event_addNewTaskButtonActionPerformed

        private void editTask1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editTask1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_editTask1ActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addNewTaskButton;
        private javax.swing.JButton allCompletedTasks;
        private javax.swing.JLabel completedTask1;
        private javax.swing.JLabel completedTask2;
        private javax.swing.JLabel completedTask3;
        private javax.swing.JButton editTask1;
        private javax.swing.JButton editTask2;
        private javax.swing.JButton editTask3;
        private javax.swing.JButton editTask4;
        private javax.swing.JButton goBackButton;
        private javax.swing.JPanel headerPanel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel profileLabel;
        private javax.swing.JButton showAllTask;
        private javax.swing.JComboBox<String> sorting;
        private javax.swing.JCheckBox task1;
        private javax.swing.JLabel task1DueDate;
        private javax.swing.JLabel task1groups;
        private javax.swing.JCheckBox task2;
        private javax.swing.JLabel task2DueDate;
        private javax.swing.JLabel task2groups;
        private javax.swing.JCheckBox task3;
        private javax.swing.JLabel task3DueDate;
        private javax.swing.JLabel task3groups;
        private javax.swing.JCheckBox task4;
        private javax.swing.JLabel task4DueDate;
        private javax.swing.JLabel task4groups;
        // End of variables declaration//GEN-END:variables
}
