package groupProf;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

import javax.swing.*;
import Classes.DB;
import GroupChat.ChatPanel;
import Menu.Menu;
import adminControls.AdminControlsPanel;
import Classes.*;

/**
 *
 * @author AmirrezaKhoshbakht
 */
public class groupProf extends javax.swing.JPanel {
        Group group;
        User user;

        /**
         * Creates new form groupProf
         */
        public groupProf(Group group, User user) {
                this.user = user;
                this.group = group;
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                headerPanel = new javax.swing.JPanel();
                goBackButton = new javax.swing.JButton();
                profileLabel = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jButton2 = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jList1 = new javax.swing.JList<>();
                jComboBox1 = new javax.swing.JComboBox<>();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();

                goBackButton.setText("< Groups");
                goBackButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

                profileLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
                profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                profileLabel.setText("Group Profile");

                javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
                headerPanel.setLayout(headerPanelLayout);
                headerPanelLayout.setHorizontalGroup(headerPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(headerPanelLayout.createSequentialGroup()
                                                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(132, 132, 132)
                                                .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 295,
                                                                Short.MAX_VALUE)
                                                .addGap(336, 336, 336)));
                headerPanelLayout.setVerticalGroup(headerPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(headerPanelLayout.createSequentialGroup().addGroup(headerPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(goBackButton).addComponent(profileLabel,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 11, Short.MAX_VALUE)));

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel1.setText(group.getGroupName());
                jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

                jLabel2.setText("Refrence Number: " + group.getGroupID());

                jButton1.setText("Picture");

                jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel3.setText("Admin: " + DB.getUser(group.getMembers().get(0).id).getUsername());

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel4.setText("Member Count: " + group.getMembers().size());

                jButton2.setText("Admin Controls");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                        try {
                                openAdminControlsPanel();
                        } catch (SQLException e) {
                                // TODO Auto-generated catch block
                                e.printStackTrace();
                        }
                        }
                    });
                

                jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                String[] s = new String[6];
                s[0] = "Categories";
                s[1] = " ";
                s[2] = group.getCategories().get(0);
                if (group.getCategories().size() > 1) {
                        s[3] = group.getCategories().get(1);
                }
                if (group.getCategories().size() > 2) {
                        s[4] = group.getCategories().get(2);
                }
                if (group.getCategories().size() > 3) {
                        s[5] = group.getCategories().get(3);
                }

                jList1.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = s;

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                jScrollPane1.setViewportView(jList1);

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by", "A-Z", "Z-A" }));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel1).addGap(424, 424, 424))
                                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(423, 423, 423)
                                                                .addComponent(jLabel2))
                                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(117, 117, 117)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jButton2)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jButton1))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jComboBox1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                .addGap(130, 130, 130)));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(30, 30, 30)
                                                                                .addComponent(jButton1)
                                                                                .addGap(99, 99, 99)
                                                                                .addComponent(jLabel3)
                                                                                .addGap(33, 33, 33)
                                                                                .addComponent(jLabel4))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jScrollPane1)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jComboBox1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18).addComponent(jButton2)
                                                .addContainerGap(73, Short.MAX_VALUE)));

                jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                Object[][] o = new Object[4][2];
                o[0][0] = DB.getUser(group.getMembers().get(0).id).getUsername();
                o[0][1] = DB.getUser(group.getMembers().get(0).id).xp;
                o[1][0] = DB.getUser(group.getMembers().get(1).id).getUsername();
                o[1][1] = DB.getUser(group.getMembers().get(1).id).xp;
                if (group.getMembers().size() > 2) {
                        o[2][0] = DB.getUser(group.getMembers().get(2).id).getUsername();
                        o[2][1] = DB.getUser(group.getMembers().get(2).id).xp;
                }
                if (group.getMembers().size() > 3) {
                        o[3][0] = DB.getUser(group.getMembers().get(3).id).getUsername();
                        o[3][1] = DB.getUser(group.getMembers().get(3).id).xp;
                }

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                // new Object[][] { { "hi", 1 }, { null, null }, { null, null }, { null, null }
                                // }
                                o, new String[] { "Member", "Score" }) {
                        Class[] types = new Class[] { java.lang.String.class, java.lang.Integer.class };
                        boolean[] canEdit = new boolean[] { false, false };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane2.setViewportView(jTable1);

                jButton3.setText("Chat");
                jButton3.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {

                                // TODO change to chatScreen

                        }
                });

                jButton4.setBackground(new java.awt.Color(255, 0, 0));
                jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jButton4.setText("LeaveGroup");
                jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup().addGap(111, 111, 111)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 728,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton3).addGap(22, 22, 22))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton4).addGap(34, 34, 34)));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton3).addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 176,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                105, Short.MAX_VALUE)
                                                .addComponent(jButton4).addGap(27, 27, 27)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));

                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            openGroupChat();
                        }
                    });

        }

        public void openAdminControlsPanel() throws SQLException{

                
                JPanel otherPanel = new AdminControlsPanel(group);
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                Container contain = frame.getContentPane();                
                contain.removeAll();
                contain.add(new Menu(user), BorderLayout.WEST);
                contain.add(otherPanel, BorderLayout.CENTER);
                contain.revalidate();
                contain.setVisible(true);
        }

        public void openGroupChat(){

                JPanel otherPanel = new ChatPanel(group.getGroupID() , user);
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                Container contain = frame.getContentPane();                
                contain.removeAll();
                contain.add(new Menu(user), BorderLayout.WEST);
                contain.add(otherPanel, BorderLayout.CENTER);
                contain.revalidate();
                contain.setVisible(true);
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton goBackButton;
        private javax.swing.JPanel headerPanel;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JList<String> jList1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable jTable1;
        private javax.swing.JLabel profileLabel;
        // End of variables declaration//GEN-END:variables
}
